name: Publish
on:
  push:
    branches:
      - main
jobs:
  Verify:
    uses: ./.github/workflows/verify.yaml
  Publish:
    needs: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: '${{needs.Verify.outputs.fqin}}'