name: Publish
on:
  push:
    branches:
      - main
jobs:
  Verify:
    uses: ./.github/workflows/verify.yaml
  Publish:
    needs: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: '${{needs.Verify.outputs.fqin}}'
      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ needs.Verify.outputs.fqin }}
          registry: ghcr.io/eriknelson
          username: eriknelson
          password: ${{ secrets.GITHUB_TOKEN }}